2024-05-07 05:14:10,805 INFO    MainThread:11020 [wandb_setup.py:_flush():76] Current SDK version is 0.16.6
2024-05-07 05:14:10,805 INFO    MainThread:11020 [wandb_setup.py:_flush():76] Configure stats pid to 11020
2024-05-07 05:14:10,805 INFO    MainThread:11020 [wandb_setup.py:_flush():76] Loading settings from /root/.config/wandb/settings
2024-05-07 05:14:10,805 INFO    MainThread:11020 [wandb_setup.py:_flush():76] Loading settings from /root/mats/sae/wandb/settings
2024-05-07 05:14:10,805 INFO    MainThread:11020 [wandb_setup.py:_flush():76] Loading settings from environment variables: {}
2024-05-07 05:14:10,805 INFO    MainThread:11020 [wandb_setup.py:_flush():76] Applying setup settings: {'_disable_service': False}
2024-05-07 05:14:10,805 INFO    MainThread:11020 [wandb_setup.py:_flush():76] Inferring run settings from compute environment: {'program_relpath': 'sae/main.py', 'program_abspath': '/root/mats/sae/main.py', 'program': '/root/mats/sae/main.py'}
2024-05-07 05:14:10,805 INFO    MainThread:11020 [wandb_setup.py:_flush():76] Applying login settings: {}
2024-05-07 05:14:10,805 INFO    MainThread:11020 [wandb_init.py:_log_setup():521] Logging user logs to /root/mats/sae/wandb/run-20240507_051410-wi59t5gr/logs/debug.log
2024-05-07 05:14:10,806 INFO    MainThread:11020 [wandb_init.py:_log_setup():522] Logging internal logs to /root/mats/sae/wandb/run-20240507_051410-wi59t5gr/logs/debug-internal.log
2024-05-07 05:14:10,806 INFO    MainThread:11020 [wandb_init.py:init():561] calling init triggers
2024-05-07 05:14:10,806 INFO    MainThread:11020 [wandb_init.py:init():568] wandb.init called with sweep_config: {}
config: {}
2024-05-07 05:14:10,806 INFO    MainThread:11020 [wandb_init.py:init():586] re-initializing run, found existing run on stack: sxeuswp1
2024-05-07 05:14:10,808 INFO    MainThread:11020 [wandb_run.py:_finish():2064] finishing run jacobcd52/sae/sxeuswp1
2024-05-07 05:14:10,808 INFO    MainThread:11020 [jupyter.py:save_history():445] not saving jupyter history
2024-05-07 05:14:10,808 INFO    MainThread:11020 [jupyter.py:save_ipynb():373] not saving jupyter notebook
2024-05-07 05:14:10,808 INFO    MainThread:11020 [wandb_init.py:_jupyter_teardown():449] cleaning up jupyter logic
2024-05-07 05:14:10,808 INFO    MainThread:11020 [wandb_run.py:_atexit_cleanup():2304] got exitcode: 0
2024-05-07 05:14:10,808 INFO    MainThread:11020 [wandb_run.py:_restore():2287] restore
2024-05-07 05:14:10,808 INFO    MainThread:11020 [wandb_run.py:_restore():2293] restore done
2024-05-07 05:14:14,958 INFO    MainThread:11020 [wandb_run.py:_footer_history_summary_info():3936] rendering history
2024-05-07 05:14:14,965 INFO    MainThread:11020 [wandb_run.py:_footer_history_summary_info():3968] rendering summary
2024-05-07 05:14:14,974 INFO    MainThread:11020 [wandb_run.py:_footer_sync_info():3895] logging synced files
2024-05-07 05:14:15,133 INFO    MainThread:11020 [wandb_init.py:init():611] starting backend
2024-05-07 05:14:15,133 INFO    MainThread:11020 [wandb_init.py:init():615] setting up manager
2024-05-07 05:14:15,137 INFO    MainThread:11020 [backend.py:_multiprocessing_setup():105] multiprocessing start_methods=fork,spawn,forkserver, using: spawn
2024-05-07 05:14:15,138 INFO    MainThread:11020 [wandb_init.py:init():623] backend started and connected
2024-05-07 05:14:15,148 INFO    MainThread:11020 [wandb_run.py:_label_probe_notebook():1299] probe notebook
2024-05-07 05:14:15,148 INFO    MainThread:11020 [wandb_run.py:_label_probe_notebook():1309] Unable to probe notebook: 'NoneType' object has no attribute 'get'
2024-05-07 05:14:15,148 INFO    MainThread:11020 [wandb_init.py:init():715] updated telemetry
2024-05-07 05:14:15,155 INFO    MainThread:11020 [wandb_init.py:init():748] communicating run to backend with 90.0 second timeout
2024-05-07 05:14:16,257 INFO    MainThread:11020 [wandb_run.py:_on_init():2357] communicating current version
2024-05-07 05:14:16,390 INFO    MainThread:11020 [wandb_run.py:_on_init():2366] got version response 
2024-05-07 05:14:16,391 INFO    MainThread:11020 [wandb_init.py:init():799] starting run threads in backend
2024-05-07 05:14:16,650 INFO    MainThread:11020 [wandb_run.py:_console_start():2335] atexit reg
2024-05-07 05:14:16,650 INFO    MainThread:11020 [wandb_run.py:_redirect():2190] redirect: wrap_raw
2024-05-07 05:14:16,650 INFO    MainThread:11020 [wandb_run.py:_redirect():2255] Wrapping output streams.
2024-05-07 05:14:16,650 INFO    MainThread:11020 [wandb_run.py:_redirect():2280] Redirects installed.
2024-05-07 05:14:16,650 INFO    MainThread:11020 [wandb_init.py:init():842] run started, returning control to user process
2024-05-07 05:34:19,466 INFO    MainThread:11020 [wandb_setup.py:_flush():76] Current SDK version is 0.16.6
2024-05-07 05:34:19,467 INFO    MainThread:11020 [wandb_setup.py:_flush():76] Configure stats pid to 11020
2024-05-07 05:34:19,467 INFO    MainThread:11020 [wandb_setup.py:_flush():76] Loading settings from /root/.config/wandb/settings
2024-05-07 05:34:19,467 INFO    MainThread:11020 [wandb_setup.py:_flush():76] Loading settings from /root/mats/sae/wandb/settings
2024-05-07 05:34:19,467 INFO    MainThread:11020 [wandb_setup.py:_flush():76] Loading settings from environment variables: {}
2024-05-07 05:34:19,467 INFO    MainThread:11020 [wandb_setup.py:_flush():76] Applying setup settings: {'_disable_service': False}
2024-05-07 05:34:19,467 INFO    MainThread:11020 [wandb_setup.py:_flush():76] Inferring run settings from compute environment: {'program_relpath': 'sae/main.py', 'program_abspath': '/root/mats/sae/main.py', 'program': '/root/mats/sae/main.py'}
2024-05-07 05:34:19,467 INFO    MainThread:11020 [wandb_setup.py:_flush():76] Applying login settings: {}
2024-05-07 05:34:19,467 INFO    MainThread:11020 [wandb_init.py:_log_setup():521] Logging user logs to /root/mats/sae/wandb/run-20240507_053419-fekf26nh/logs/debug.log
2024-05-07 05:34:19,467 INFO    MainThread:11020 [wandb_init.py:_log_setup():522] Logging internal logs to /root/mats/sae/wandb/run-20240507_053419-fekf26nh/logs/debug-internal.log
2024-05-07 05:34:19,467 INFO    MainThread:11020 [wandb_init.py:_jupyter_setup():467] configuring jupyter hooks <wandb.sdk.wandb_init._WandbInit object at 0x7fcf1d053670>
2024-05-07 05:34:19,467 INFO    MainThread:11020 [wandb_init.py:init():561] calling init triggers
2024-05-07 05:34:19,467 INFO    MainThread:11020 [wandb_init.py:init():568] wandb.init called with sweep_config: {}
config: {}
2024-05-07 05:34:19,467 INFO    MainThread:11020 [wandb_init.py:init():586] re-initializing run, found existing run on stack: wi59t5gr
2024-05-07 05:34:19,469 INFO    MainThread:11020 [wandb_run.py:_finish():2064] finishing run jacobcd52/sae/wi59t5gr
2024-05-07 05:34:19,469 INFO    MainThread:11020 [wandb_run.py:_atexit_cleanup():2304] got exitcode: 0
2024-05-07 05:34:19,469 INFO    MainThread:11020 [wandb_run.py:_restore():2287] restore
2024-05-07 05:34:19,469 INFO    MainThread:11020 [wandb_run.py:_restore():2293] restore done
2024-05-07 05:34:23,655 INFO    MainThread:11020 [wandb_run.py:_footer_history_summary_info():3936] rendering history
2024-05-07 05:34:23,664 INFO    MainThread:11020 [wandb_run.py:_footer_history_summary_info():3968] rendering summary
2024-05-07 05:34:23,671 INFO    MainThread:11020 [wandb_run.py:_footer_sync_info():3895] logging synced files
